### ISSUE TITLE
entities not updating

### ISSUE THREAD

**Issue by cxFreeze** [Aohzan/hass-prixcarburant#4]
hi, my entities are not updating (unless i reboot ha)

![screenshot295](https://user-images.githubusercontent.com/19434393/180617263-7dc55e7c-cf47-42ac-b38f-771a0c0563d5.png)

`  - platform: prix_carburant
    stations:
      - xxxxxxxxx
      - xxxxxxxxx`

do you know what can i do ?

thanks

**Comment by ManTreff** [comment]
Salut, j'ai le mm problème. En rechargeant l'intégration ca se met a jours...

**Comment by tikismoke** [comment]
Pareil obligé de recharger l'intégration.

**Comment by Quentame** [comment]
Hi !

That's actually a big issue indeed.

I personally update all entities at once by reloading the config entry with an automation, at specific times.


Here is how to do this:
```yaml
alias: UPDATE - Prix carburant
trigger:
  - platform: time
    at: "08:00:00"
  - platform: time
    at: "18:00:00"
action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id: sensor.station_XXX
mode: single
```
Update the automation as you wish.
`homeassistant.reload_config_entry` requires only one entity to update all the config, adding more is useless.

De rien 😉

**Comment by karba78** [comment]
pareil +1 same issue

**Comment by pbranly** [comment]
Will you implement the correction in order to have at least an update every hour ? 
This issue is a show stopper for me before switching from the vinguerha one to yours 
Regards 
Philippe

**Comment by Otiel** [comment]
@Quentame I'm getting a memory leak while using an automation like the one you provided. For instance, when trigger is every one hour:

![image](https://user-images.githubusercontent.com/3851902/195153101-01757873-36ce-4aeb-9936-81bbe08eec71.png)

The spikes down are when I'm forced to restart Home Assistant because not enough memory is available.

Have you noticed the same issue?

**Comment by Otiel** [comment]
@Aohzan Why has this been closed? Issue is still present in 2.5.1

**Comment by Aohzan** [comment]
the original issue have been solved, and like nobody answer for the memory problem since I closed it
I don't have the memory problem, are you sure it come from this integration ? what automation did you use ?

**Comment by Otiel** [comment]
@Aohzan Sorry, I meant I still have the issue of entities not updating automatically.

**Comment by Otiel** [comment]
@Aohzan Any update on this? Is there any log I can provide to help debug this? My entities are still not updating.

**Comment by Aohzan** [comment]
hello,
did you try the last beta version ? it should update every 30 minutes
I will add a button to ask price refresh manually

**Comment by Otiel** [comment]
Hi @Aohzan 

Sorry for the late reply, I have tried the 3.0.0 beta versions, then v3.0.0 and v3.1.0 for several days in order to be sure of the integration behavior. I notice the same behavior for all versions: entities are not updated automatically.

![image](https://github.com/Aohzan/hass-prixcarburant/assets/3851902/c05d6b28-e36d-4ca9-88ff-ccedb724f682)

However, entities are correctly updated when I restart Home Assistant or when I use the new `button.prix_carburant_refresh_prices`.

What can I do to check what's wrong with the automatic refresh?

**Comment by xontik** [comment]
Is there something we can contribute yo help diagnose ? I have the same bug no update at all on any entities

**Comment by tikismoke** [comment]
Personally I made a node red flow that reload the integration every 12h.

**Comment by Aohzan** [comment]
The issue is fixed in 3.2.0, I added an option to choose the time between two upgrades (default to 4 hours)
Otherwise, you don't have to reload all the integration, you can just call the button entity which only reload prices

**Comment by Otiel** [comment]
Looks good to me now, prices are correctly refreshed. Thanks a lot @Aohzan ❤️ 

![image](https://github.com/Aohzan/hass-prixcarburant/assets/3851902/933aa06e-2063-4fa8-b527-47895b3f3e80)
